# Default values for chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicas: 1

appName: sqs-to-s3-download

global:
  dockerRepository: nexus-docker-public-hosted.ossim.io

image:
  name: sqs-to-s3-download
  tag: latest
  pullPolicy: Always


nfs:
  server: o2-nfs.private.ossim.io

storage: 16G


volumeNameBlacksky: blacksky-data
volumeMountPathBlackSky: /maxar-blacksky-data

volumeNameSkysat: skysat-data
volumeMountPathSkysat: /maxar-skysat-data


sqsQueue: arn:aws:sqs:us-east-1:320588532383:3pa-test
#sqsQueue: arn:aws:sqs:us-east-1:576113035271:gegd-tpc
#sqsQueue: arn:aws:sqs:us-east-1:12345678910:my-cool-test-queue
