apiVersion: apps/v1
kind: Deployment
metadata:
  name: "gfo-processing"
spec:
  selector:
    matchLabels:
      app: "gfo-processing"
  template:
    metadata:
      labels:
        app: "gfo-processing"
    spec:
      containers:
        - name: "gfo-processing"
          image: "nexus-docker-public-hosted.ossim.io/gfo-processing"
#          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            timeoutSeconds: 3
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            timeoutSeconds: 3
            failureThreshold: 10
#          volumeMounts:
#            - mountPath: /3pa-blacksky-data
#              name: blacksky-data
#            - mountPath: /3pa-skysat-data
#              name: skysat-data
#      volumes:
#        - name: blacksky-data
#          persistentVolumeClaim:
#            claimName: gfo-processing-blacksky-data-pvc
#        - name: skysat-data
#          persistentVolumeClaim:
#            claimName: gfo-processing-skysat-data-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: "gfo-processing"
spec:
  selector:
    app: "gfo-processing"
  type: ClusterIP
  ports:
    - protocol: "TCP"
      port: 8080
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: gfo-processing
  labels:
    app: gfo-processing
data:
  application.yaml: |-
    app:
      sqs:
        #queue: aws-sqs://arn:aws:sqs:us-east-1:576113035271:gegd-tpc-test
        queue: aws-sqs://arn:aws:sqs:us-east-1:320588532383:3pa-test
