apiVersion: apps/v1
kind: Deployment
metadata:
  name: "sqs-to-s3-download"
spec:
  selector:
    matchLabels:
      app: "sqs-to-s3-download"
  template:
    metadata:
      labels:
        app: "sqs-to-s3-download"
    spec:
      containers:
        - name: "sqs-to-s3-download"
          image: "nexus-docker-public-hosted.ossim.io/sqs-to-s3-download"
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            timeoutSeconds: 3
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            timeoutSeconds: 3
            failureThreshold: 10
          volumeMounts:
            - mountPath: /3pa-blacksky
              name: blacksky-data
            - mountPath: /3pa-skysat
              name: skysat-data
      volumes:
        - name: blacksky-data
          persistentVolumeClaim:
            claimName: sqs-to-s3-download-blacksky-data-pvc
        - name: skysat-data
          persistentVolumeClaim:
            claimName: sqs-to-s3-download-skysat-data-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: "sqs-to-s3-download"
spec:
  selector:
    app: "sqs-to-s3-download"
  type: ClusterIP
  ports:
    - protocol: "TCP"
      port: 8080
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: sqs-to-s3-download
  labels:
    app: sqs-to-s3-download
data:
  application.yaml: |-
    app:
      sqs:
        queue: arn:aws:sqs:us-east-1:576113035271:gegd-tpc
