apiVersion: apps/v1
kind: Deployment
metadata:
  name: "gfo-processing"
spec:
  selector:
    matchLabels:
      app: "gfo-processing"
  template:
    metadata:
      labels:
        app: "gfo-processing"
    spec:
      containers:
        - name: "gfo-processing"
          image: "nexus-docker-public-hosted.ossim.io/gfo-processing"
          ports:
            - name: http
              containerPort: 8080
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            timeoutSeconds: 3
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            timeoutSeconds: 3
            failureThreshold: 10
---
apiVersion: v1
kind: Service
metadata:
  name: "gfo-processing"
spec:
  selector:
    app: "gfo-processing"
  type: LoadBalancer
  ports:
    - protocol: "TCP"
      port: 8080
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: gfo-processing
  labels:
    app: gfo-processing
data:
  application.yaml: |-
    app:
      sqs:
        queue: gegd-tpc
      s3:
        bucket:
          SkySatTo: nga-skysat-data-test
          SkySatFrom: nga-non-diode-o1
          BlackSkyTo: nga-blacksky-data-test
          BlackSkyFrom: kno-gv-o1

        processed:
          dir: ingest