apiVersion: skaffold/v2beta4
kind: Config
metadata:
  name: sqs-to-s3-download
build:
  artifacts:
  - image: nexus-docker-public-hosted.ossim.io/sqs-to-s3-download
    jib: {}
  tagPolicy:
    sha256: {}

deploy:
  kubectl:
    manifests:
    - k8s.yml
