---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-sqs-to-s3-download
  labels:
    app: sqs-to-s3-download
data:
  application.yaml: |-
    app:
      sqs:
        queue: {{ .Values.sqsQueue }}