---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-sqs-to-s3-download
  labels:
    app: sqs-to-s3-download
data:
  application.yaml: |-
    app:
      sqs:
        queue: aws-sqs://arn:aws:sqs:us-east-1:576113035271:gegd-tpc-test
        #queue: aws-sqs://arn:aws:sqs:us-east-1:320588532383:3pa-test